development:
  adapter: postgresql
  database: my_golf_app_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: my_golf_app_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: my_golf_app_production
  pool: 5
  timeout: 5000